local map = vim.keymap.set
map("n", "<leader>tt", function()
	require("neotest").run.run()
end, { desc = "Run the nearest test" })
map("n", "<leader>tT", function()
	require("neotest").run.run(vim.fn.expand("%"))
end, { desc = "Test the current file" })
map("n", "<leader>td", function()
	require("neotest").run.run({ strategy = "dap", suite = true })
end, { desc = "Debug the nearest test" })
map("n", "<leader>tc", function()
	require("neotest").run.stop()
end, { desc = "Stop the current test" })
map("n", "<leader>ta", function()
	require("neotest").run.attach()
end, { desc = "Attach to the current test" })

map("n", "<leader>to", function()
	require("neotest").output.open()
end, { desc = "Attach to the current test" })
