return {
	-- {
	-- 	-- Theme inspired by Atom
	-- 	-- "nordtheme/vim",
	-- 	-- priority = 1000,
	-- 	-- config = function()
	-- 	-- 	vim.cmd.colorscheme("nord")
	-- 	-- 	vim.cmd("highlight Normal guibg='#0f0f0f' guifg=white")
	-- 	-- 	vim.o.background = "dark"
	-- 	-- end,
	-- },
	-- {
	-- 	'shaunsingh/nord.nvim',
	-- 	config = function()
	-- 		-- vim.cmd.colorscheme("nord")
	--
	-- 		vim.g.nord_contrast = true
	-- 		vim.g.nord_borders = false
	-- 		vim.g.nord_disable_background = true
	-- 		vim.g.nord_italic = false
	-- 		vim.g.nord_uniform_diff_background = true
	-- 		vim.g.nord_bold = false
	-- 		require('nord').set()
	-- 	end
	-- }
}
